name: "Docker Build & Push"
description: "Reusable composite action to build and push Docker images with tagging"

inputs:
  service:
    description: "Service name"
    required: true
  compose-file:
    description: "Path to docker-compose.yml"
    required: true
  registry:
    description: "Container registry host"
    default: cr.alkhwarizmi.online
  username:
    description: "Registry username"
    required: true
  password:
    description: "Registry password"
    required: true



runs:
  using: "composite"
  steps:
    - name: Set IMAGE_TAG
      shell: bash
      run: |
        set -euo pipefail
        if [ "${{ github.event_name }}" = "release" ]; then
          IMAGE_TAG="${{ github.event.release.tag_name }}"
        elif [[ "${GITHUB_REF_TYPE}" = "tag" && "${GITHUB_REF_NAME}" == v* ]]; then
          IMAGE_TAG="${GITHUB_REF_NAME}"
        else
          IMAGE_TAG="master-${GITHUB_SHA::7}"
        fi
        echo "Resolved IMAGE_TAG=$IMAGE_TAG"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Debug IMAGE_TAG
      shell: bash
      run: echo "Next step sees IMAGE_TAG=$IMAGE_TAG"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}


    - name: Show resolved image
      shell: bash
      run: docker compose -f ${{ inputs.compose-file }} config | sed -n '/image:/p'

    - name: Build with Docker Compose
      shell: bash
      run: docker compose -f ${{ inputs.compose-file }} build --progress=plain

    - name: Push with Docker Compose
      shell: bash
      run: docker compose -f ${{ inputs.compose-file }} push

    - name: Add channel tag :master
      if: startsWith(env.IMAGE_TAG, 'master-')
      shell: bash
      run: |
        BASE=${{ inputs.registry }}/${{ inputs.service }}
        docker pull $BASE:${IMAGE_TAG}
        docker tag  $BASE:${IMAGE_TAG} $BASE:master
        docker push $BASE:master

    - name: Publish semver aliases
      if: startsWith(env.IMAGE_TAG, 'v')
      shell: bash
      run: |
        BASE=${{ inputs.registry }}/${{ inputs.service }}
        FULL=${IMAGE_TAG#v}
        MAJ=${FULL%%.*}
        MIN=${FULL%.*}
        docker pull $BASE:${IMAGE_TAG}
        docker tag  $BASE:${IMAGE_TAG} $BASE:${FULL}
        docker tag  $BASE:${IMAGE_TAG} $BASE:${MIN}
        docker tag  $BASE:${IMAGE_TAG} $BASE:${MAJ}
        docker push $BASE:${FULL}
        docker push $BASE:${MIN}
        docker push $BASE:${MAJ}

    - name: Publish sha- tag
      shell: bash
      run: |
        BASE=${{ inputs.registry }}/${{ inputs.service }}
        SHORT_SHA=${GITHUB_SHA::7}
        docker pull $BASE:${IMAGE_TAG}
        docker tag  $BASE:${IMAGE_TAG} $BASE:sha-${SHORT_SHA}
        docker push $BASE:sha-${SHORT_SHA}
