name: "Checkout Microservices"
description: "Checks out selected microservice repos"

inputs:
  token:
    description: "GitHub PAT with repo access"
    required: true
  include_cms:
    description: "Include CMS microservice"
    default: "true"
  include_schools:
    description: "Include Schools microservice"
    default: "true"
  include_lms:
    description: "Include LMS microservice"
    default: "true"
  include_payment:
    description: "Include Payment microservice"
    default: "true"
  include_delivery:
    description: "Include Delivery microservice"
    default: "true"
  include_chatbot:
    description: "Include ChatBot microservice"
    default: "true"
  ref:
    description: "Branch or tag to checkout"
    default: master


runs:
  using: "composite"
  steps:
    - name: Checkout ClassLibraryCore
      uses: actions/checkout@v4
      with:
        repository: Khz-DevOps/ClassLibraryCore
        token: ${{ inputs.token }}
        path: ClassLibraryCore
        ref: ${{ inputs.ref }}

    - name: Checkout CMS-Core
      if: ${{ inputs.include_cms == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: Khz-DevOps/CMS-Core
        token: ${{ inputs.token }}
        path: MicroServicesCore/SaaS/CMS
        ref: ${{ inputs.ref }}

    - name: Checkout Schools
      if: ${{ inputs.include_schools == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: Khz-DevOps/School
        token: ${{ inputs.token }}
        path: MicroServicesCore/SaaS/School
        ref: ${{ inputs.ref }}

    - name: Checkout LMSPlatform
      if: ${{ inputs.include_lms == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: Khz-DevOps/LMSPlatform
        token: ${{ inputs.token }}
        path: MicroServicesCore/LMSPlatform
        ref: ${{ inputs.ref }}

    - name: Checkout PaymentService
      if: ${{ inputs.include_payment == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: Khz-DevOps/PaymentService
        token: ${{ inputs.token }}
        path: MicroServicesCore/PaymentService
        ref: ${{ inputs.ref }}

    - name: Checkout DeliveryService
      if: ${{ inputs.include_delivery == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: Khz-DevOps/DeliveryService
        token: ${{ inputs.token }}
        path: MicroServicesCore/DeliveryService
        ref: ${{ inputs.ref }}

    - name: Checkout ChatBotService
      if: ${{ inputs.include_chatbot == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: Khz-DevOps/ChatBotService
        token: ${{ inputs.token }}
        path: MicroServicesCore/ChatBotService
        ref: ${{ inputs.ref }}
