name: "Docker Build"
description: "Build Docker image"

inputs:
  compose-file:
    description: "Path to the Docker Compose file"
    required: true
  image_tag:     
    description: "Tag to use for the Docker image"
    required: true

runs:
  using: "composite"
  steps:

    - name: Build
      shell: bash
      run: docker compose -f ${{ inputs.compose-file }} build --progress=plain
      env:
        IMAGE_TAG: ${{ inputs.image_tag }}
        
