name: "Docker Tag Semver"
description: "Publish semver aliases for vX.Y.Z tags"

inputs:
  registry:
    description: "Container registry host"
    default: cr.alkhwarizmi.online

  service:
    description: "Service name"
    required: true

  image_tag:
    description: "Image tag in semver format (e.g., v1.2.3)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Semver tagging
      if: startsWith(inputs.image_tag, 'v')
      shell: bash
      run: |
        BASE=${{ inputs.registry }}/${{ inputs.service }}
        TAG="${{ inputs.image_tag }}"   # e.g. v1.2.3
        FULL="${TAG#v}"                 # remove leading v → 1.2.3
        MAJ="${FULL%%.*}"               # → 1
        MIN="${FULL%.*}"                 # → 1.2
        docker pull $BASE:$TAG
        docker tag $BASE:$TAG $BASE:$FULL
        docker tag $BASE:$TAG $BASE:$MIN
        docker tag $BASE:$TAG $BASE:$MAJ
        docker push $BASE:$FULL
        docker push $BASE:$MIN
        docker push $BASE:$MAJ
