name: "Docker Tag Semver"
description: "Publish semver aliases for vX.Y.Z tags"

inputs:
  registry:
    description: "Container registry host"
    default: cr.alkhwarizmi.online

  service:
    description: "Service name"
    required: true

  image_tag:
    description: "Image tag in semver format (e.g., v1.2.3)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Semver tagging
      if: startsWith(inputs.image_tag, 'v')
      shell: bash
      run: |
        BASE=${{ inputs.registry }}/${{ inputs.service }}
        FULL=${{ inputs.image_tag#v }}
        MAJ=${FULL%%.*}
        MIN=${FULL%.*}
        docker pull $BASE:${{ inputs.image_tag }}
        docker tag $BASE:${{ inputs.image_tag }} $BASE:${FULL}
        docker tag $BASE:${{ inputs.image_tag }} $BASE:${MIN}
        docker tag $BASE:${{ inputs.image_tag }} $BASE:${MAJ}
        docker push $BASE:${FULL}
        docker push $BASE:${MIN}
        docker push $BASE:${MAJ}
